[package]
name = "cpu_usage_indicator"
version = "0.1.0"
authors = ["zoomdy <mingdu.zheng@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = { version = "3.1" }
